service: get-offen

provider:
  name: aws
  region: eu-central-1
  runtime: go1.x
  cfnRole: lambda.amazonaws.com

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  get:
    environment:
      GITHUB_REPO: offen/offen
    handler: bin/get
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{param1}
          method: any
      - http:
          path: /{param1}/{param2}
          method: any
