version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.14
    working_directory: ~/get
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Build
          command: make build
      - persist_to_workspace:
          root: ~/get
          paths:
            - bin/*

  deploy:
    docker:
      - image: cimg/node:14.4
    working_directory: ~/get
    steps:
      - checkout
      - attach_workspace:
          at: ~/get
      - run:
          name: Install serverless
          command: |
            mkdir -p ~/.npm-global
            npm config set prefix '~/.npm-global'
            npm install serverless@^1.72.0 -g
            echo 'export PATH=~/.npm-global/bin/:$PATH' >> $BASH_ENV
      - run:
          name: Deploy
          command: sls deploy

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: AWS
          filters:
            branches:
              only:
                - master

