version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.7
    working_directory: ~/get
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: make build DOCKER_TAG=test
  deploy:
    docker:
      - image: cimg/base:2020.06
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'c3:09:7c:f4:a5:2c:66:45:79:53:f4:b4:ce:42:e7:bf'
      - checkout
      - run:
          name: Run keyscan
          command: |
            ssh-keyscan -H storage.offen.dev >> ~/.ssh/known_hosts
      - run:
          name: Configure git
          command: |
            git config --global user.email "hioffen@posteo.de"
            git config --global user.name "Offen Deploy Bot"
            git remote add deployment root@storage.offen.dev:offen/get.git
      - run:
          name: Push to deployment
          command: |
            git push deployment master -f 2>&1 | tee out.txt
            grep -v "ERR_DEPLOYMENT_FAILED" out.txt > /dev/null
      - run:
          name: Check service health
          command: |
            curl -sSI https://get.offen.dev

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master

