version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.06
    working_directory: ~/get
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: make build
      - run:
          name: Check if image needs to be pushed
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              echo "Not on master branch, nothing to do ..."
              circleci-agent step halt
            fi
      - docker/install-docker-credential-helper
      - docker/configure-docker-credentials-store
      - run:
          name: Push to Docker Hub
          command: |
            echo "$DOCKER_ACCESSTOKEN" | docker login --username offen --password-stdin
            docker push offen/get:latest

  deploy:
    docker:
      - image: cimg/base:2020.06
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'c3:09:7c:f4:a5:2c:66:45:79:53:f4:b4:ce:42:e7:bf'
      - checkout
      - run:
          name: Run keyscan
          command: |
            ssh-keyscan -H get.offen.dev >> ~/.ssh/known_hosts
      - run:
          name: Configure git
          command: |
            git config --global user.email "hioffen@posteo.de"
            git config --global user.name "Offen Deploy Bot"
            git remote add deployment root@get.offen.dev:offen/get.git
      - run:
          name: Push to deployment
          command: |
            git push deployment master -f 2>&1 | tee out.txt
            grep -v "ERR_DEPLOYMENT_FAILED" out.txt > /dev/null
      - run:
          name: Check service health
          command: |
            curl -sSI https://get.offen.dev/healthz

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master

orbs:
  docker: circleci/docker@1.0.1
